name: movieScraperBot

on: [push]

jobs:
  movieScrapping:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: |
        pip install BeautifulSoup4
    - name: movie scrapping
      run: | 
        python3 ./bin/movieScraper.py

 
