name: movieScraperBot

on: [push]

jobs:
  movieScrapping:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: |
        pip install BeautifulSoup4
        
    - name: movie scrapping
      id: movieScrapping
      run: | 
        python3 ./bin/movieScraper.py > output.txt

    - name: send telegram message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message_file: output.txt

 
