name: movieScraperBot

on: [push]

jobs:
  movieScrapping:
    runs-on: ubuntu-latest
    outputs:
      movieTiles: ${{ steps.movieScrapping.outputs.titles }}
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: |
        pip install BeautifulSoup4
    - name: movie scrapping
      id: movieScrapping
      run: | 
        echo "::set-output name=titles::python3 ./bin/movieScraper.py"

  telegramNotification:
    runs-on: ubuntu-latest
    needs: movieScrapping
    steps:
      - name: send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{needs.movieScrapping.outputs.movieTiles}}

 
