name: movieScraperBot

on:
  schedule:
    - cron: '0 6 * * *'
    
  workflow_dispatch:

jobs:
  movieScraping:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: movie scraping
      id: movieScraping
      run: | 
        python3 ./bin/movieScraper.py | tee latest_movies.txt

    - name: send a telegram message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message_file: latest_movies.txt

 
